[package]
name = "wordler"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
dashmap = "6.1.0"
hashbrown = { version = "0.16.1", features = ["rayon"] }
rand = "0.9.2"
rayon = "1.11"
